import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const contracts = [
  {
    artifact: "out/RevealReceiptStore.sol/RevealReceiptStore.json",
    abi: "abis/RevealReceiptStore.json",
    exportName: "revealReceiptStoreAbi"
  },
  {
    artifact: "out/PurchaseRefRegistry.sol/PurchaseRefRegistry.json",
    abi: "abis/PurchaseRefRegistry.json",
    exportName: "purchaseRefRegistryAbi"
  }
];

const generatedTsPath = path.join(rootDir, "package/src/abis.generated.ts");
const generatedTs = [
  "// This file is generated by scripts/extract-abis.mjs.",
  "// Do not edit it manually.",
  ""
];

for (const contract of contracts) {
  const artifactPath = path.join(rootDir, contract.artifact);
  let artifactJson;

  try {
    artifactJson = await readFile(artifactPath, "utf8");
  } catch (error) {
    throw new Error(
      `Missing Foundry artifact for ${contract.exportName}: ${contract.artifact}. Run npm run build:contracts first.`,
      { cause: error }
    );
  }

  const artifact = JSON.parse(artifactJson);

  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Foundry artifact ${contract.artifact} does not contain an ABI array.`);
  }

  const abiJson = `${JSON.stringify(artifact.abi, null, 2)}\n`;
  const abiPath = path.join(rootDir, contract.abi);

  await mkdir(path.dirname(abiPath), { recursive: true });
  await writeFile(abiPath, abiJson, "utf8");

  generatedTs.push(`export const ${contract.exportName} = ${abiJson.trim()} as const;`, "");
}

await mkdir(path.dirname(generatedTsPath), { recursive: true });
await writeFile(generatedTsPath, `${generatedTs.join("\n")}\n`, "utf8");

console.log(`Wrote ${contracts.length} ABI JSON files and package/src/abis.generated.ts.`);
