import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const contracts = [
  {
    artifact: "out/NotaReceiptStore.sol/NotaReceiptStore.json",
    abi: "abis/NotaReceiptStore.json",
    exportName: "notaReceiptStoreAbi"
  },
  {
    artifact: "out/PurchaseRefRegistry.sol/PurchaseRefRegistry.json",
    abi: "abis/PurchaseRefRegistry.json",
    exportName: "purchaseRefRegistryAbi"
  }
];

const checkedInAbis = [
  {
    abi: "abis/RevealReceiptStore.json",
    exportName: "revealReceiptStoreAbi"
  }
];

const generatedTsPath = path.join(rootDir, "package/src/abis.generated.ts");
const generatedTs = [
  "// This file is generated by scripts/extract-abis.mjs.",
  "// Do not edit it manually.",
  ""
];

for (const contract of contracts) {
  const artifactPath = path.join(rootDir, contract.artifact);
  let artifactJson;

  try {
    artifactJson = await readFile(artifactPath, "utf8");
  } catch (error) {
    throw new Error(
      `Missing Foundry artifact for ${contract.exportName}: ${contract.artifact}. Run npm run build:contracts first.`,
      { cause: error }
    );
  }

  const artifact = JSON.parse(artifactJson);

  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Foundry artifact ${contract.artifact} does not contain an ABI array.`);
  }

  const abiJson = `${JSON.stringify(artifact.abi, null, 2)}\n`;
  const abiPath = path.join(rootDir, contract.abi);

  await mkdir(path.dirname(abiPath), { recursive: true });
  await writeFile(abiPath, abiJson, "utf8");

  generatedTs.push(`export const ${contract.exportName} = ${abiJson.trim()} as const;`, "");
}

for (const checkedInAbi of checkedInAbis) {
  const abiPath = path.join(rootDir, checkedInAbi.abi);
  let abiJson;

  try {
    abiJson = await readFile(abiPath, "utf8");
  } catch (error) {
    throw new Error(
      `Missing checked-in ABI for ${checkedInAbi.exportName}: ${checkedInAbi.abi}.`,
      { cause: error }
    );
  }

  const abi = JSON.parse(abiJson);

  if (!Array.isArray(abi)) {
    throw new Error(`Checked-in ABI ${checkedInAbi.abi} must be an ABI-only JSON array.`);
  }

  generatedTs.push(`export const ${checkedInAbi.exportName} = ${JSON.stringify(abi, null, 2)} as const;`, "");
}

await mkdir(path.dirname(generatedTsPath), { recursive: true });
await writeFile(generatedTsPath, `${generatedTs.join("\n")}\n`, "utf8");

console.log(`Wrote ${contracts.length} generated ABI JSON files and package/src/abis.generated.ts.`);
